#!/bin/bash

FORBIDDEN='%TODO:BEFORE_COMMIT%

git diff --cached --name-only | \
  xargs grep --with-filename -n $FORBIDDEN && \
  echo "COMMIT REJECTED: TODOs which are due before commit were found. Please attend to them before committing" && exit 1
